name: Deploy Multiple Projects

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare Public Directory
        run: |
          mkdir -p public
          # Copiamos cada proyecto a su propia subcarpeta dentro de public
          cp -r dashboardVentas public/
          cp -r miPortfolio public/
          cp -r spotifyUIclone public/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public
          target-folder: .